name: Package Application with Pyinstaller (Darwin)

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy build files
      run: rsync -av --exclude='builds' * builds/mac  
    
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'builds/mac/app.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'BetterCinema_Darwin'
        options: --onefile
