name: Package Application with Pyinstaller (Darwin)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'app.py'
        requirements: 'requirements.txt'
        options: --onefile
    - name: Rename Application
      run: mv dist/app dist/BetterCinema_Darwin

    - uses: actions/upload-artifact@v2
      with:
        name: BetterCinema-Linux
        path: dist/BetterCinema_Darwin # or path/to/artifact

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/BetterCinema_Darwin
