name: Package Application with Pyinstaller (Darwin)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'app.py'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'BetterCinema_Darwin'
        options: --onefile
